{% set name = "unique-uncertainty" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unique_uncertainty-{{ version }}.tar.gz
  sha256: 0709f5d11366a9eb47f1dc6a0dc0216e5bd35858fe1528076f1c0a5bb10935d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<=3.12.1
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<=3.12.1
    - colorcet >=3.0,<=3.0.1
    - ipykernel >=6.29,<=6.29.2
    - jinja2 >=3.1,<=3.1.3
    - matplotlib-base >=3.6,<=3.8.2
    - numpy >=1.19,<=1.26.4
    - pandas >=2.0,<=2.2.0
    - pyarrow <=16.1.0
    - pyyaml >=6.0,<=6.0.1
    - rdkit ==2023.09.1
    - ruamel.yaml >=0.17
    - scikit-learn >=1.3,<=1.4.0
    - scipy >=1.10,<=1.12.0
    - seaborn >=0.13,<=0.13.2
    - shapely >=2.0,<=2.0.2
    - statsmodels >=0.13.3,<=0.14.2
    - tqdm >=4.65,<=4.66.2

test:
  imports:
    - unique
    - unique.pipeline
  commands:
    # `pip check` fails with error "unique-uncertainty <version> requires rdkit, which is not installed."
    # However, `rdkit` is explicitly stated in the recipe/dependency list and is correctly installed in the test build.
    # See: https://github.com/conda-forge/staged-recipes/pull/27696#discussion_r1776813050 and following answer. 
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Novartis/UNIQUE
  summary: "UNIQUE is a Python package for benchmarking uncertainty estimation and quantification methods for Machine Learning models predictions."
  description: |
    UNIQUE provides methods for quantifying and evaluating the uncertainty of Machine Learning (ML) models predictions. The library allows to:

    - combine and benchmark multiple uncertainty quantification (UQ) methods simultaneously;

    - evaluate the goodness of UQ methods against established metrics;

    - generate intuitive visualizations to qualitatively assess how well the computed UQ methods represent the actual model uncertainty;

    - enable the users to get a comprehensive overview of their ML model’s performances from an uncertainty quantification perspective.

    UNIQUE is a model-agnostic tool, meaning that it does not depend on any specific ML model building platform nor provides any ML model training functionality. It only requires the user to input their model’s inputs and predictions.
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://opensource.nibr.com/UNIQUE
  dev_url: https://github.com/Novartis/UNIQUE

extra:
  recipe-maintainers:
    - mtdhuynh
    - gscebba
